# 6. Risk Register

| # | Risk | Likelihood | Impact | Mitigation |
|---|------|-----------|--------|------------|
| 1 | **LLM produces hallucinated content contradicting NCERT** | Medium | Critical | RAG-anchored prompts with explicit "only use textbook content" instructions. Post-hoc validation: for assessments, compare LLM-generated answers against question bank ground truth. Log all teaching responses for human spot-checks. |
| 2 | **Per-session cost exceeds ₹20 budget** | Medium | High | Token budgeting: cap conversation history to 10 messages (~4K tokens). Use GPT-4o-mini for non-teaching tasks. Limit TTS to key explanations (not every response). Limit DALL·E to max 1 image per session. Monitor token usage dashboard daily. |
| 3 | **Streaming JSON parsing breaks mid-stream** | Medium | Medium | Use incremental JSON parser (e.g., `ijson`). Design response schema so `response_text` is the first field — stream it directly while buffering the rest. Fallback: if JSON parse fails, treat entire response as plain text and skip multimodal triggers. |
| 4 | **RAG retrieval returns irrelevant chunks** | Medium | High | Filter by `chapter_id` AND `subtopic` (not just vector similarity). Use small, focused chunks (512 tokens). Log retrieved chunks for every session for quality auditing. If retrieval quality is poor, add BM25 hybrid search as a second pass. |
| 5 | **ElevenLabs TTS latency >5s degrades UX** | Low | Medium | Use ElevenLabs "turbo" model. Generate audio asynchronously — don't block text display. Cache synthesized audio by content hash. Fallback: browser-native `SpeechSynthesis` API (lower quality but instant). |
| 6 | **State machine gets stuck in an invalid state** | Low | High | Explicit transition validation — every state change checked against allowed transitions enum. Redis TTL of 2 hours auto-expires abandoned sessions. Health-check endpoint that lists sessions stuck in non-terminal states for >1 hour. |
| 7 | **3-day timeline insufficient for full MVP** | High | High | Phases are ordered by priority — Phase 0-3 delivers a usable text-only teaching loop. Phases 4+ are additive. If time-constrained, ship Phases 0-3 as "v0.1" and continue. Multimodal and WhatsApp are enhancers, not blockers. |
| 8 | **Twilio WhatsApp sandbox limitations in demo** | Medium | Low | Sandbox requires recipients to opt-in via a specific message. For MVP demo: pre-register parent test numbers. Document the sandbox limitation. Production migration requires WhatsApp Business API approval (1-2 weeks). |
| 9 | **Large NCERT PDFs cause ingestion timeout** | Low | Medium | Process PDFs asynchronously in background task. Chunk in batches of 50. Add progress tracking to ingestion jobs. Set generous timeout (10 min). Split very large PDFs (>100 pages) into chapter-level uploads. |
| 10 | **Persona/context prompt grows too large, exceeding token limits** | Low | Medium | Hard cap rolling summaries at 500 tokens. Prune oldest insights when merging new ones. Monitor total system prompt size — alert if >6K tokens. Reserve 8K tokens minimum for conversation history + RAG chunks within 128K context window. |
